import {DropdownOption} from '@ironsource/fusion-ui/components/dropdown-option/entities';

export const MOCK_DUAL_ITEMS: DropdownOption[] = [
    {id: 1, title: 'Mario Speedwagon'},
    {id: 2, title: 'Petey Cruiser'},
    {id: 3, title: 'Anna Sthesia'},
    {id: 4, title: 'Paul Molive'},
    {id: 5, title: 'Anna Mull'},
    {id: 6, title: 'Gail Forcewind'},
    {id: 7, title: 'Paige Turner'},
    {id: 8, title: 'Bob Frapples'},
    {id: 9, title: 'Walter Melon'},
    {id: 10, title: 'Nick R. Bocker'},
    {id: 11, title: 'Barb Ackue'},
    {id: 12, title: 'Buck Kinnear'},
    {id: 13, title: 'Greta Life'},
    {id: 14, title: 'Ira Membrit'},
    {id: 15, title: 'Shonda Leer'},
    {id: 16, title: 'Brock Lee'},
    {id: 17, title: 'Maya Didas'},
    {id: 18, title: 'Rick O`Shea'},
    {id: 19, title: 'Pete Sariya'},
    {id: 20, title: 'Monty Carlo'},
    {id: 21, title: 'Mario Speed'},
    {id: 22, title: 'Harry Potter'},
    {id: 23, title: 'Ron Wisely'},
    {id: 24, title: 'Severus Snape'},
    {id: 25, title: 'Hermione Granger'},
    {id: 26, title: 'Tom Hanks'},
    {id: 27, title: 'The Rock'},
    {id: 28, title: 'Tom Hardy'},
    {id: 29, title: 'Tom Hiddleston'},
    {id: 30, title: 'Captain America'},
    {id: 31, title: 'Black Panther'},
    {id: 32, title: 'Black Widow'},
    {id: 33, title: 'Green Lantern'},
    {id: 34, title: 'Chris Evans'},
    {id: 35, title: 'Robert Downey Jr.'},
    {id: 36, title: 'Robert Redford'},
    {id: 37, title: 'Winter Soldier'},
    {id: 38, title: 'Bucky Barnes'},
    {id: 39, title: 'Sam Wilson'},
    {id: 40, title: 'Bruce Banner'}
];
