#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

BRANCH_NAME="$(git branch | grep \* | sed -e 's/\* //g')"
if [[ -z "$BRANCH_NAME" ]] || [ "$BRANCH_NAME" != "master" ]; then
    # if branch is different then master do not run entities
    exit 0
else
    echo -e "\t${RED}Push Aborted - Pushing to master only available from github pull requests${NC}"
    exit 1
fi

