name: CI-Main

on:
  push:

concurrency:
  group: fusion_ci

jobs:
  # --- Do Code Formatter and Linter check
  code-quality:
    name: 'Code Quality Check'
    uses: ironSource/fusion-ui/.github/workflows/step_linter.yml@master
    with:
      branch_name: ${{ github.ref_name}}

  # --- Do Unit-Test check
  unit-tests:
    name: 'UnitTests'
    uses: ironSource/fusion-ui/.github/workflows/step_unit_tests.yml@master
    with:
      branch_name: ${{ github.ref_name }}

  # --- Do Git Leaks check
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
