name: CI-Main

on:
  push:

concurrency:
  group: fusion_ci

jobs:
  # --- Do Code Formatter and Linter check
  code-quality:
    name: 'Code Quality Check'
    uses: ironSource/fusion-ui/.github/workflows/step_linter.yml@master
    with:
      branch_name: ${{ github.ref_name}}

  # --- Do Unit-Test check
  unit-test:
    name: 'UnitTests'
    uses: ironSource/fusion-ui/.github/workflows/step_unit_tests.yml@master
    with:
      branch_name: ${{ github.ref_name }}
