name: Dependency-Review

on:
  pull_request:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: [self-hosted, x64, linux, eks, us, demand, dev]
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2
        with:
          fail-on-severity: high
#          allow-licenses: MIT
