name: Dependency-Review

on:
  push:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: [self-hosted, demand]
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - run: |
          echo "base: ${{ github.event.before }}"
          echo "head: ${{ github.sha }}"

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2
        with:
          base-ref: ${{ github.event.before }}
          head-ref: ${{ github.sha }}
          fail-on-severity: high
          allow-licenses: MIT
