name: Dependency-Review and Git Leaks

on:
  pull_request:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: [self-hosted, demand]
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2
        with:
          fail-on-severity: high
          allow-licenses: MIT

  gitleaks:
    runs-on: ubuntu-20.04
    steps:
      - name: Add Homebrew to $PATH
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - uses: actions/checkout@v3

      - name: Install GitLeaks
        run: |
          brew install gitleaks

      - name: gitleaks-action
        run: |
          gitleaks --verbose detect --log-opts --since="2021-11-25"
