name: Dependency-Review

on:
  pull_request: # push not supported see https://github.com/actions/dependency-review-action/issues/252

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: [self-hosted, demand]
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2
        with:
          fail-on-severity: high
          allow-licenses: MIT
