name: CI-CodeCheck

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  startCI:
    if: ${{ github.actor != '${{ secrets.BOT_USER }}' }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate Short SHA and Unique runer id
        id: vars
        run: |
          echo ::set-output name=sha_short::${GITHUB_SHA::7}
          echo ::set-output name=uuid::${{ env.BRANCH_NAME }}:${GITHUB_SHA::7}:${GITHUB_RUN_ID}

      - name: Trigger Code Validate
        id: trigger
        timeout-minutes: 7
        uses: ironSource/action-trigger-workflow@v1
        with:
          owner: ${{ secrets.TRIGGERED_OWNER }}
          repo: ${{ secrets.TRIGGERED_REPO }}
          github_token: ${{ secrets.PAT_TOKEN }}
          workflow_file_name: ci.yml
          job_uuid: "${{ steps.vars.outputs.uuid }}"
          inputs: '{ "repository": "${{github.repository}}", "branch_name": "${{ env.BRANCH_NAME }}", "user": "${{github.actor}}", "job_uuid": "${{ steps.vars.outputs.uuid }}", "sha": "${{ steps.vars.outputs.sha_short }}", "event_name": "${{github.event_name}}", "event_action": "${{github.event.action}}"}'
