name: Issue Created Notification

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: [self-hosted, x64, linux, eks, us, demand, dev]
    steps:
      - uses: actions/checkout@v2

      - name: 'Notify'
        uses: ironSource/action-slack-notification@v1
        with:
          channel: fusion-notifications
          username: FusionUI-CI
          status: "warning"
          icon_url: "https://avatars.githubusercontent.com/t/5433436?s=32&v=4"
          message: "${{github.actor}} create an ${{ github.event.issue.labels[0].name }} ISSUE - ${{ github.event.issue.number }} ${{ github.event.issue.title }}. https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }}"
          slack_webhook: ${{ secrets.SLACK_PATH }}
