name: Step-Dependency-Review

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch name to dependency-review"
        required: true
        default: "master"

env:
  BRANCH_NAME: ${{ github.event.inputs.branch_name || inputs.branch_name }}

jobs:
  dependency-review:
    runs-on: [self-hosted, demand]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2
        with:
          fail-on-severity: high
          allow-licenses: MIT
