name: Test-For dev checks

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch name to Test"
        required: true
        default: "master"

env:
  BRANCH_NAME: ${{ github.event.inputs.branch_name || inputs.branch_name }}

jobs:
  code-quality:
    runs-on: [self-hosted, x64, linux, eks, us, demand-amd64, dev]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm ci
